### PR TITLE
Update CommunityPlugins.ts

### PR DESCRIPTION
**Pull request by HugoImaios**
update link for rollup-plugin-copy

### CODE REVIEW

**Review by patak-cat — APPROVED** [review]
Thanks!

**Comment by HugoImaios** [comment]
you're welcome !
@patak-dev I've fixed the outdated link with this PR, but I'm still not sure if this link is enough to consider `rollup-plugin-copy` as Covered. What do you think about adding a link to https://github.com/sapphi-red/vite-plugin-static-copy#readme instead ? (and itself points to the official Vite doc if needed)

**Comment by patak-cat** [comment]
That's a good idea, PR welcome!

**Comment by HugoImaios** [comment]
Will do, see you there :wave:

**Pull request merged**
